sudo: required
addons:
  ssh_known_hosts:
    - ${DEPLOY_HOST}
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- docker build -t hakanhuriyet/todo-client  -f Dockerfile.dev .
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- docker run hakanhuriyet/todo-client npm run test
deploy:
  edge: true
  provider: script
  skip_cleanup: true,
  script: rsync -r --quiet --delete ${TRAVIS_BUILD_DIR}/public/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
