version: '3'
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "4200:4200"
        volumes: 
            - '.:/app'
            - '/app/node_modules'
        command: npm run start
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - '.:/app'
            - '/app/node_modules'
        command: npm run test